export type VehicleBrand =
  | "maruti" | "hyundai" | "tata" | "mahindra" | "toyota" | "force" | "honda"
  | "kia" | "renault" | "nissan" | "mg" | "volkswagen" | "skoda" | "ford"
  | "datsun" | "jeep" | "isuzu" | "school_bus" | "other";

export const vehicleBrands: { value: VehicleBrand; label: string }[] = [
  { value: "maruti", label: "Maruti Suzuki" },
  { value: "hyundai", label: "Hyundai" },
  { value: "tata", label: "Tata" },
  { value: "mahindra", label: "Mahindra" },
  { value: "toyota", label: "Toyota" },
  { value: "kia", label: "Kia" },
  { value: "renault", label: "Renault" },
  { value: "honda", label: "Honda" },
  { value: "nissan", label: "Nissan" },
  { value: "mg", label: "MG (Morris Garages)" },
  { value: "volkswagen", label: "Volkswagen" },
  { value: "skoda", label: "Skoda" },
  { value: "ford", label: "Ford" },
  { value: "datsun", label: "Datsun" },
  { value: "jeep", label: "Jeep" },
  { value: "isuzu", label: "Isuzu" },
  { value: "force", label: "Force" },
  { value: "school_bus", label: "School Bus" },
  { value: "other", label: "Other (not listed)" },
];

export const vehicleModels: Record<VehicleBrand, { value: string; label: string }[]> = {
  maruti: [
    { value: "swift", label: "Swift" },
    { value: "dzire", label: "Dzire" },
    { value: "ertiga", label: "Ertiga" },
    { value: "xl6", label: "XL6" },
    { value: "alto", label: "Alto" },
    { value: "alto_k10", label: "Alto K10" },
    { value: "baleno", label: "Baleno" },
    { value: "celerio", label: "Celerio" },
    { value: "wagon_r", label: "Wagon R" },
    { value: "s_presso", label: "S-Presso" },
    { value: "vitara_brezza", label: "Vitara Brezza" },
    { value: "fronx", label: "Fronx" },
    { value: "grand_vitara", label: "Grand Vitara" },
    { value: "ignis", label: "Ignis" },
    { value: "ciaz", label: "Ciaz" },
  ],
  hyundai: [
    { value: "aura", label: "Aura" },
    { value: "i10", label: "i10" },
    { value: "i20", label: "i20" },
    { value: "grand_i10", label: "Grand i10 Nios" },
    { value: "xcent", label: "Xcent" },
    { value: "venue", label: "Venue" },
    { value: "creta", label: "Creta" },
    { value: "alcazar", label: "Alcazar" },
    { value: "elantra", label: "Elantra" },
    { value: "tucson", label: "Tucson" },
    { value: "verna", label: "Verna" },
  ],
  tata: [
    { value: "tigor", label: "Tigor" },
    { value: "tiago", label: "Tiago" },
    { value: "nexon", label: "Nexon" },
    { value: "punch", label: "Punch" },
    { value: "harrier", label: "Harrier" },
    { value: "safari", label: "Safari" },
    { value: "indica", label: "Indica" },
    { value: "indigo", label: "Indigo" },
    { value: "altroz", label: "Altroz" },
    { value: "curvv", label: "Curvv" },
  ],
  mahindra: [
    { value: "scorpio", label: "Scorpio" },
    { value: "scorpio_classic", label: "Scorpio Classic" },
    { value: "scorpio_n", label: "Scorpio N" },
    { value: "xuv500", label: "XUV500" },
    { value: "xuv300", label: "XUV300" },
    { value: "xuv700", label: "XUV700" },
    { value: "bolero", label: "Bolero" },
    { value: "bolero_neo", label: "Bolero Neo" },
    { value: "thar", label: "Thar" },
    { value: "marazzo", label: "Marazzo" },
    { value: "xylo", label: "Xylo" },
    { value: "nuvosport", label: "Nuvosport" },
  ],
  toyota: [
    { value: "innova", label: "Innova Crysta" },
    { value: "innova_hycross", label: "Innova HyCross" },
    { value: "fortuner", label: "Fortuner" },
    { value: "legender", label: "Fortuner Legender" },
    { value: "glanza", label: "Glanza" },
    { value: "urban_cruiser", label: "Urban Cruiser Hyryder" },
    { value: "etios", label: "Etios" },
    { value: "etios_liva", label: "Etios Liva" },
    { value: "yaris", label: "Yaris" },
    { value: "camry", label: "Camry" },
  ],
  kia: [
    { value: "seltos", label: "Seltos" },
    { value: "sonet", label: "Sonet" },
    { value: "carens", label: "Carens" },
    { value: "ev6", label: "EV6" },
  ],
  renault: [
    { value: "kwid", label: "Kwid" },
    { value: "triber", label: "Triber" },
    { value: "duster", label: "Duster" },
    { value: "kiger", label: "Kiger" },
    { value: "lodgy", label: "Lodgy" },
  ],
  honda: [
    { value: "amaze", label: "Amaze" },
    { value: "city", label: "City" },
    { value: "city_hybrid", label: "City Hybrid" },
    { value: "jazz", label: "Jazz" },
    { value: "wr_v", label: "WR-V" },
    { value: "elevate", label: "Elevate" },
    { value: "brio", label: "Brio" },
    { value: "br_v", label: "BR-V" },
  ],
  nissan: [
    { value: "magnite", label: "Magnite" },
    { value: "kicks", label: "Kicks" },
    { value: "sunny", label: "Sunny" },
    { value: "terrano", label: "Terrano" },
  ],
  mg: [
    { value: "astor", label: "Astor" },
    { value: "hector", label: "Hector" },
    { value: "hector_plus", label: "Hector Plus" },
    { value: "gloster", label: "Gloster" },
    { value: "zs_ev", label: "ZS EV" },
    { value: "comet_ev", label: "Comet EV" },
  ],
  volkswagen: [
    { value: "polo", label: "Polo" },
    { value: "vento", label: "Vento" },
    { value: "taigun", label: "Taigun" },
    { value: "virtus", label: "Virtus" },
    { value: "tiguan", label: "Tiguan" },
  ],
  skoda: [
    { value: "rapid", label: "Rapid" },
    { value: "slavia", label: "Slavia" },
    { value: "kushaq", label: "Kushaq" },
    { value: "octavia", label: "Octavia" },
    { value: "superb", label: "Superb" },
  ],
  ford: [
    { value: "figo", label: "Figo" },
    { value: "aspire", label: "Aspire" },
    { value: "ecosport", label: "EcoSport" },
    { value: "endeavour", label: "Endeavour" },
    { value: "freestyle", label: "Freestyle" },
  ],
  datsun: [
    { value: "redi_go", label: "redi-GO" },
    { value: "go", label: "GO" },
    { value: "go_plus", label: "GO+" },
  ],
  jeep: [
    { value: "compass", label: "Compass" },
    { value: "meridian", label: "Meridian" },
    { value: "wrangler", label: "Wrangler" },
  ],
  isuzu: [
    { value: "d_max", label: "D-Max" },
    { value: "mu_x", label: "MU-X" },
  ],
  force: [
    { value: "cruiser", label: "Cruiser" },
    { value: "traveller", label: "Traveller" },
    { value: "trax_toofan", label: "Trax Toofan" },
    { value: "gurkha", label: "Gurkha" },
  ],
  school_bus: [
    { value: "standard", label: "Standard School Bus" },
  ],
  other: [],
};

export function getModelsByBrand(brand: VehicleBrand) {
  return vehicleModels[brand] || [];
}
