// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin/dashboard" | "/auth/sign-in" | "/booking" | "/contact" | "/driver/dashboard" | "/driver/register" | "/drivers/[slug]" | "/faqs" | "/live-activity" | "/privacy" | "/safety" | "/search" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/drivers/[id]/approval" | "/api/admin/drivers/pending" | "/api/driver-quotes" | "/api/driver-quotes/[id]/accept" | "/api/driver/requests" | "/api/drivers/[id]/availability" | "/api/drivers/onboard" | "/api/marketplace/metrics" | "/api/ride-requests" | "/api/ride-requests/[id]/quotes" | "/api/uploads/signed-url"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin/dashboard": {}
  "/api/admin/drivers/[id]/approval": { "id": string; }
  "/api/admin/drivers/pending": {}
  "/api/driver-quotes": {}
  "/api/driver-quotes/[id]/accept": { "id": string; }
  "/api/driver/requests": {}
  "/api/drivers/[id]/availability": { "id": string; }
  "/api/drivers/onboard": {}
  "/api/marketplace/metrics": {}
  "/api/ride-requests": {}
  "/api/ride-requests/[id]/quotes": { "id": string; }
  "/api/uploads/signed-url": {}
  "/auth/sign-in": {}
  "/booking": {}
  "/contact": {}
  "/driver/dashboard": {}
  "/driver/register": {}
  "/drivers/[slug]": { "slug": string; }
  "/faqs": {}
  "/live-activity": {}
  "/privacy": {}
  "/safety": {}
  "/search": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
